### ISSUE TITLE
particle system

### ISSUE THREAD

**Issue by co0p** [co0p/tankism#26]
- [x] system keeping track of particles available (defines max limit)
- [x] system recycles particles (constant memory footprint)
- [x] emitter component defining start conditions for emitting done by system

```
type emitterconfig struct {
color: ...
position_min: ... 
position_max: ... 
velocity_min: ... 
velocity_max ...
lifetime_min: ...
lifetime_max: ...
spawnrate: ...  
}

type particle struct {
x, y:...
vx, vy:...
lifetime:...
color: ...
}
```

**Comment by jevbelikov** [comment]
- dirt/debris
- weather (e.g raindrops) ?

**Comment by co0p** [comment]
In order to maintain a fixed set of particles we could use the obejctpool pattern..   https://github.com/theodesp/go-object-pool/blob/master/fixed.go
